
import amir1 from './amir1.jpg'
import amir2 from './amir2.jpg'
import amir3 from './amir3.jpg'
import dots from './dots.png'
import place from './place.svg'
import NexusFaviIcon from './NexusBerry_favi.jpg'
import swtLogo from './swtLogo.webp'
import calc from './Capture.jpg'
import calc2 from './amir1.jpg'
import html from './html.svg'
import css from './css.svg'
import js from './javascript.svg'
import nodjs from './nodeJS.svg'
import  TypeScript  from './typescript.svg'
import react from './react.svg'
import nextjs from './nextJS.svg'
import git from './git.svg'
import mongodb from './mongoDB.svg'
import tailwindcss from './tailwind.svg'
import bootstrap from './bootstrap.svg'
import shadcn from './shadcn.png'
import care1 from './care1.jpg'
import care2 from './care2.jpg'
import care3 from './care3.jpg'
import care4 from './care4.jpg'
import zada from './zada.jpg'
import store1 from './store1.jpg'
import store2 from './store2.jpg'
import store3 from './store3.jpg'
import store4 from  './store4.jpg'
import store5 from   './store4.jpg'
import kfc1 from './kfc1.jpg'
import kfc2 from './kfc2.jpg'
import kfc3 from './kfc3.jpg'
import q1 from './q1.jpg'
import q2 from './q2.jpg'
import q3 from './q3.jpg'


export {
    amir1, amir2, dots,place,NexusFaviIcon,swtLogo, amir3,calc, calc2, css,html,bootstrap, nextjs,
    react, nodjs, git,tailwindcss, js, TypeScript, mongodb, shadcn, care1,care2,care3,care4,zada,
    store1,store2,store3,store4,store5,kfc1,kfc2,kfc3,q1,q2,q3,
}
